# Generated by Django 5.0.3 on 2024-04-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='images/')),
                ('cloudinary_url', models.URLField(blank=True)),
                ('first_name', models.CharField(default=True, max_length=100)),
                ('last_name', models.CharField(default=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default=True, max_length=100)),
                ('email_address', models.EmailField(default=True, max_length=100)),
                ('pincode', models.CharField(default=True, max_length=20)),
                ('phone_number', models.CharField(default=True, max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
