# Generated by Django 5.0.3 on 2024-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_registration_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('cloudinary_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
